-- Explain the current data_blocks merge shape without modifying production data.
--
-- This is a controlled reproducer for:
--
--     INSERT INTO data_blocks (id_file, data_object_id, _order, data)
--     SELECT id_file, data_object_id, _order, data
--     FROM fod_persist_block_stage
--     WHERE data IS NOT NULL
--     ON CONFLICT (data_object_id, _order)
--     DO UPDATE SET id_file = EXCLUDED.id_file, data = EXCLUDED.data
--     WHERE data_blocks.id_file IS DISTINCT FROM EXCLUDED.id_file
--        OR data_blocks.data IS DISTINCT FROM EXCLUDED.data;
--
-- The runtime staging table is temporary and connection-local, so this script
-- creates representative temporary tables and indexes instead. WAL numbers on
-- temporary tables are not production-representative; the useful signal is the
-- executor shape, buffer activity, and relative insert/update cost.

\pset pager off

SET search_path TO pg_temp, fod, public;

SELECT now() AS captured_at;

SELECT
    current_database() AS database_name,
    current_schema() AS current_schema,
    current_setting('search_path') AS search_path;

SELECT 'real data_blocks reference count before temp reproducer' AS section;

SELECT count(*) AS real_data_blocks_rows_before
FROM data_blocks;

CREATE TEMP TABLE fod_explain_data_blocks (
    id_block INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_file INTEGER NOT NULL,
    data_object_id INTEGER NOT NULL,
    _order INTEGER NOT NULL,
    data BYTEA NOT NULL
);

CREATE INDEX fod_explain_data_blocks_data_object_id
    ON fod_explain_data_blocks (data_object_id);

CREATE UNIQUE INDEX fod_explain_data_blocks_object_order
    ON fod_explain_data_blocks (data_object_id, _order);

CREATE TEMP TABLE fod_persist_block_stage (
    id_file BIGINT NOT NULL,
    data_object_id BIGINT NOT NULL,
    _order BIGINT NOT NULL,
    data BYTEA,
    crc32 BIGINT
);

SELECT 'temporary reproducer shape' AS section;

SELECT
    16384 AS stage_rows,
    4096 AS payload_bytes_per_row,
    'temp target with primary key, data_object_id index, and unique (data_object_id, _order)' AS target_shape;

WITH payload AS (
    SELECT decode(repeat('ab', 4096), 'hex') AS data
)
INSERT INTO fod_persist_block_stage (id_file, data_object_id, _order, data, crc32)
SELECT
    900001,
    900001,
    series.block_index,
    payload.data,
    NULL::BIGINT
FROM generate_series(0, 16383) AS series(block_index)
CROSS JOIN payload;

ANALYZE fod_persist_block_stage;
ANALYZE fod_explain_data_blocks;

SELECT 'EXPLAIN fresh insert into empty temp target' AS section;

EXPLAIN (ANALYZE, BUFFERS, WAL, VERBOSE)
INSERT INTO fod_explain_data_blocks (id_file, data_object_id, _order, data)
SELECT id_file, data_object_id, _order, data
FROM fod_persist_block_stage
WHERE data IS NOT NULL
ON CONFLICT (data_object_id, _order)
DO UPDATE SET id_file = EXCLUDED.id_file, data = EXCLUDED.data
WHERE fod_explain_data_blocks.id_file IS DISTINCT FROM EXCLUDED.id_file
   OR fod_explain_data_blocks.data IS DISTINCT FROM EXCLUDED.data;

ANALYZE fod_explain_data_blocks;

SELECT 'EXPLAIN conflict update with identical payload' AS section;

EXPLAIN (ANALYZE, BUFFERS, WAL, VERBOSE)
INSERT INTO fod_explain_data_blocks (id_file, data_object_id, _order, data)
SELECT id_file, data_object_id, _order, data
FROM fod_persist_block_stage
WHERE data IS NOT NULL
ON CONFLICT (data_object_id, _order)
DO UPDATE SET id_file = EXCLUDED.id_file, data = EXCLUDED.data
WHERE fod_explain_data_blocks.id_file IS DISTINCT FROM EXCLUDED.id_file
   OR fod_explain_data_blocks.data IS DISTINCT FROM EXCLUDED.data;

TRUNCATE fod_persist_block_stage;

WITH payload AS (
    SELECT decode(repeat('cd', 4096), 'hex') AS data
)
INSERT INTO fod_persist_block_stage (id_file, data_object_id, _order, data, crc32)
SELECT
    900002,
    900001,
    series.block_index,
    payload.data,
    NULL::BIGINT
FROM generate_series(0, 16383) AS series(block_index)
CROSS JOIN payload;

ANALYZE fod_persist_block_stage;

SELECT 'EXPLAIN conflict update with changed payload and id_file' AS section;

EXPLAIN (ANALYZE, BUFFERS, WAL, VERBOSE)
INSERT INTO fod_explain_data_blocks (id_file, data_object_id, _order, data)
SELECT id_file, data_object_id, _order, data
FROM fod_persist_block_stage
WHERE data IS NOT NULL
ON CONFLICT (data_object_id, _order)
DO UPDATE SET id_file = EXCLUDED.id_file, data = EXCLUDED.data
WHERE fod_explain_data_blocks.id_file IS DISTINCT FROM EXCLUDED.id_file
   OR fod_explain_data_blocks.data IS DISTINCT FROM EXCLUDED.data;

SELECT 'temporary target final count' AS section;

SELECT
    count(*) AS temp_data_blocks_rows,
    count(DISTINCT data_object_id) AS temp_data_objects,
    count(DISTINCT id_file) AS temp_id_files
FROM fod_explain_data_blocks;

SELECT 'real data_blocks reference count after temp reproducer' AS section;

SELECT count(*) AS real_data_blocks_rows_after
FROM data_blocks;
