-- Explain the data_blocks merge shape on temporary clones with configurable
-- heap/index fillfactor. This script does not modify real FOD tables.
--
-- psql variables:
--   fillfactor        table fillfactor, 10..100
--   index_fillfactor  index fillfactor, 10..100
--   stage_rows        staged rows to generate
--   payload_bytes     BYTEA payload size per staged row

\set ON_ERROR_STOP on
\pset pager off

SET search_path TO pg_temp, fod, public;

SELECT now() AS captured_at;

SELECT
    :'fillfactor'::integer AS heap_fillfactor,
    :'index_fillfactor'::integer AS index_fillfactor,
    :'stage_rows'::integer AS stage_rows,
    :'payload_bytes'::integer AS payload_bytes,
    current_database() AS database_name,
    current_setting('search_path') AS search_path;

SELECT CASE
    WHEN :'fillfactor'::integer BETWEEN 10 AND 100
     AND :'index_fillfactor'::integer BETWEEN 10 AND 100
     AND :'stage_rows'::integer > 0
     AND :'payload_bytes'::integer > 0
    THEN 'validated'
    ELSE (1 / 0)::text
END AS parameter_validation;

SELECT 'real data_blocks reference count before temp fillfactor reproducer' AS section;

SELECT count(*) AS real_data_blocks_rows_before
FROM data_blocks;

CREATE TEMP TABLE fod_explain_data_blocks_ff (
    id_block INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_object_id INTEGER NOT NULL,
    _order INTEGER NOT NULL,
    data BYTEA NOT NULL
) WITH (fillfactor = :fillfactor);

CREATE INDEX fod_explain_data_blocks_ff_data_object_id
    ON fod_explain_data_blocks_ff (data_object_id)
    WITH (fillfactor = :index_fillfactor);

CREATE UNIQUE INDEX fod_explain_data_blocks_ff_object_order
    ON fod_explain_data_blocks_ff (data_object_id, _order)
    WITH (fillfactor = :index_fillfactor);

CREATE TEMP TABLE fod_persist_block_stage_ff (
    data_object_id BIGINT NOT NULL,
    _order BIGINT NOT NULL,
    data BYTEA,
    crc32 BIGINT
);

SELECT 'temporary fillfactor reproducer shape' AS section;

SELECT
    :'stage_rows'::integer AS stage_rows,
    :'payload_bytes'::integer AS payload_bytes_per_row,
    :'fillfactor'::integer AS heap_fillfactor,
    :'index_fillfactor'::integer AS index_fillfactor,
    'temp target with primary key, data_object_id index, and unique (data_object_id, _order)' AS target_shape;

WITH payload AS (
    SELECT decode(repeat('ab', :'payload_bytes'::integer), 'hex') AS data
)
INSERT INTO fod_persist_block_stage_ff (data_object_id, _order, data, crc32)
SELECT
    910001,
    series.block_index,
    payload.data,
    NULL::BIGINT
FROM generate_series(0, :'stage_rows'::integer - 1) AS series(block_index)
CROSS JOIN payload;

ANALYZE fod_persist_block_stage_ff;
ANALYZE fod_explain_data_blocks_ff;

SELECT 'EXPLAIN fillfactor fresh insert into empty temp target' AS section;

EXPLAIN (ANALYZE, BUFFERS, WAL, VERBOSE)
INSERT INTO fod_explain_data_blocks_ff (data_object_id, _order, data)
SELECT data_object_id, _order, data
FROM fod_persist_block_stage_ff
WHERE data IS NOT NULL
ON CONFLICT (data_object_id, _order)
DO UPDATE SET data = EXCLUDED.data
WHERE fod_explain_data_blocks_ff.data IS DISTINCT FROM EXCLUDED.data;

DO $$
BEGIN
    PERFORM pg_stat_force_next_flush();
EXCEPTION WHEN undefined_function THEN
    NULL;
END $$;

SELECT 'temp stats after fresh insert' AS section;

SELECT
    n_tup_ins,
    n_tup_upd,
    n_tup_hot_upd,
    n_tup_del,
    n_live_tup,
    n_dead_tup
FROM pg_stat_all_tables
WHERE relid = 'pg_temp.fod_explain_data_blocks_ff'::regclass;

ANALYZE fod_explain_data_blocks_ff;

SELECT 'EXPLAIN fillfactor conflict update with identical payload' AS section;

EXPLAIN (ANALYZE, BUFFERS, WAL, VERBOSE)
INSERT INTO fod_explain_data_blocks_ff (data_object_id, _order, data)
SELECT data_object_id, _order, data
FROM fod_persist_block_stage_ff
WHERE data IS NOT NULL
ON CONFLICT (data_object_id, _order)
DO UPDATE SET data = EXCLUDED.data
WHERE fod_explain_data_blocks_ff.data IS DISTINCT FROM EXCLUDED.data;

DO $$
BEGIN
    PERFORM pg_stat_force_next_flush();
EXCEPTION WHEN undefined_function THEN
    NULL;
END $$;

SELECT 'temp stats after identical conflict' AS section;

SELECT
    n_tup_ins,
    n_tup_upd,
    n_tup_hot_upd,
    n_tup_del,
    n_live_tup,
    n_dead_tup
FROM pg_stat_all_tables
WHERE relid = 'pg_temp.fod_explain_data_blocks_ff'::regclass;

TRUNCATE fod_persist_block_stage_ff;

WITH payload AS (
    SELECT decode(repeat('cd', :'payload_bytes'::integer), 'hex') AS data
)
INSERT INTO fod_persist_block_stage_ff (data_object_id, _order, data, crc32)
SELECT
    910001,
    series.block_index,
    payload.data,
    NULL::BIGINT
FROM generate_series(0, :'stage_rows'::integer - 1) AS series(block_index)
CROSS JOIN payload;

ANALYZE fod_persist_block_stage_ff;

SELECT 'EXPLAIN fillfactor conflict update with changed payload' AS section;

EXPLAIN (ANALYZE, BUFFERS, WAL, VERBOSE)
INSERT INTO fod_explain_data_blocks_ff (data_object_id, _order, data)
SELECT data_object_id, _order, data
FROM fod_persist_block_stage_ff
WHERE data IS NOT NULL
ON CONFLICT (data_object_id, _order)
DO UPDATE SET data = EXCLUDED.data
WHERE fod_explain_data_blocks_ff.data IS DISTINCT FROM EXCLUDED.data;

DO $$
BEGIN
    PERFORM pg_stat_force_next_flush();
EXCEPTION WHEN undefined_function THEN
    NULL;
END $$;

SELECT 'temp stats after changed conflict' AS section;

SELECT
    n_tup_ins,
    n_tup_upd,
    n_tup_hot_upd,
    n_tup_del,
    n_live_tup,
    n_dead_tup
FROM pg_stat_all_tables
WHERE relid = 'pg_temp.fod_explain_data_blocks_ff'::regclass;

SELECT 'temporary target final count' AS section;

SELECT
    count(*) AS temp_data_blocks_rows,
    count(DISTINCT data_object_id) AS temp_data_objects,
    pg_size_pretty(pg_relation_size('pg_temp.fod_explain_data_blocks_ff'::regclass)) AS temp_heap_size,
    pg_size_pretty(pg_total_relation_size('pg_temp.fod_explain_data_blocks_ff'::regclass)) AS temp_total_size
FROM fod_explain_data_blocks_ff;

SELECT 'real data_blocks reference count after temp fillfactor reproducer' AS section;

SELECT count(*) AS real_data_blocks_rows_after
FROM data_blocks;
