#!/usr/bin/env python3
# Compute deltas between two FOD PostgreSQL WAL snapshot files.
#
# Input files are generated by scripts/perf/pg/wal_snapshot.sql and contain
# key=value rows.
#
# Usage:
#
#     python3 scripts/perf/pg/wal_delta.py before.txt after.txt

from __future__ import annotations

from decimal import Decimal, InvalidOperation
from pathlib import Path
import sys


DELTA_KEYS = [
    "wal_records",
    "wal_fpi",
    "wal_bytes",
    "wal_buffers_full",
    "wal_write",
    "wal_sync",
    "wal_write_time",
    "wal_sync_time",
    "checkpoints_timed",
    "checkpoints_req",
    "checkpoint_write_time",
    "checkpoint_sync_time",
    "buffers_checkpoint",
    "buffers_clean",
    "maxwritten_clean",
    "buffers_backend",
    "buffers_backend_fsync",
    "buffers_alloc",
]


def parse_snapshot(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or "=" not in line:
            continue
        key, value = line.split("=", 1)
        data[key.strip()] = value.strip()
    return data


def decimal_value(data: dict[str, str], key: str) -> Decimal:
    raw = data.get(key, "0")
    if raw == "":
        return Decimal(0)
    try:
        return Decimal(raw)
    except InvalidOperation as exc:
        raise ValueError(f"{key} is not numeric: {raw!r}") from exc


def format_decimal(value: Decimal) -> str:
    if value == value.to_integral_value():
        return str(int(value))
    return format(value.normalize(), "f")


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print("Usage: wal_delta.py BEFORE_SNAPSHOT AFTER_SNAPSHOT", file=sys.stderr)
        return 2

    before_path = Path(argv[1])
    after_path = Path(argv[2])

    if not before_path.exists():
        print(f"ERROR: before snapshot not found: {before_path}", file=sys.stderr)
        return 2
    if not after_path.exists():
        print(f"ERROR: after snapshot not found: {after_path}", file=sys.stderr)
        return 2

    before = parse_snapshot(before_path)
    after = parse_snapshot(after_path)

    print(f"before_file={before_path}")
    print(f"after_file={after_path}")
    print(f"before_captured_at={before.get('captured_at', '')}")
    print(f"after_captured_at={after.get('captured_at', '')}")
    print(f"before_wal_stats_reset={before.get('wal_stats_reset', '')}")
    print(f"after_wal_stats_reset={after.get('wal_stats_reset', '')}")
    print(f"before_bgwriter_stats_reset={before.get('bgwriter_stats_reset', '')}")
    print(f"after_bgwriter_stats_reset={after.get('bgwriter_stats_reset', '')}")

    print("warning_wal_stats_reset_changed=" + ("1" if before.get("wal_stats_reset") != after.get("wal_stats_reset") else "0"))
    print("warning_bgwriter_stats_reset_changed=" + ("1" if before.get("bgwriter_stats_reset") != after.get("bgwriter_stats_reset") else "0"))

    for key in DELTA_KEYS:
        delta = decimal_value(after, key) - decimal_value(before, key)
        print(f"{key}_delta={format_decimal(delta)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
