[package]
name = "fod-rust-monitor"
version.workspace = true
edition = "2021"
rust-version.workspace = true

[lib]
name = "fod_rust_monitor"
path = "src/lib.rs"

[[bin]]
name = "fod-monitor"
path = "src/main.rs"

[dependencies]
fod_rust_runtime = { package = "fod-rust-runtime", path = "../rust_runtime" }
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
